version: "3"
services:
  web:
    image: r501/jobs:test
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 25M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
